name: Gradle CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Linting with ktlint
      run: gradle lintKotlin

    - name: Test with Gradle
      run: gradle test
